/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CropType = IDL.Variant({
  'onion' : IDL.Null,
  'groundnut' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlertCondition = IDL.Record({
  'active' : IDL.Bool,
  'above' : IDL.Bool,
  'targetPrice' : IDL.Nat,
  'marketId' : IDL.Nat,
  'cropType' : CropType,
  'isPersistent' : IDL.Bool,
});
export const Time = IDL.Int;
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notificationType' : IDL.Text,
  'userPrincipal' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
  'delivered' : IDL.Bool,
});
export const PriceRecord = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'date' : Time,
  'validated' : IDL.Bool,
  'pricePerKg' : IDL.Nat,
  'marketId' : IDL.Nat,
  'cropType' : CropType,
});
export const NotificationPreference = IDL.Record({
  'notificationTypes' : IDL.Vec(IDL.Text),
  'smsEnabled' : IDL.Bool,
  'notificationFrequency' : IDL.Nat,
  'pushEnabled' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'notificationPreferences' : NotificationPreference,
  'name' : IDL.Text,
});
export const Market = IDL.Record({
  'id' : IDL.Nat,
  'region' : IDL.Text,
  'name' : IDL.Text,
  'location' : IDL.Text,
});
export const LivePriceRecord = IDL.Record({
  'region' : IDL.Text,
  'pricePerKg' : IDL.Nat,
  'state' : IDL.Text,
  'timestamp' : Time,
  'cropType' : CropType,
  'market' : IDL.Text,
});
export const TransactionRecord = IDL.Record({
  'pricePerKg' : IDL.Float64,
  'mobileNumber' : IDL.Text,
  'weightKg' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'timestamp' : IDL.Int,
  'laborName' : IDL.Text,
  'farmerName' : IDL.Text,
});
export const MarketSummary = IDL.Record({
  'averagePrice' : IDL.Nat,
  'maxPrice' : IDL.Nat,
  'priceTrend' : IDL.Vec(IDL.Nat),
  'minPrice' : IDL.Nat,
  'totalRecords' : IDL.Nat,
});
export const TrendsData = IDL.Record({
  'monthlyTrends' : IDL.Vec(MarketSummary),
  'weeklyTrends' : IDL.Vec(MarketSummary),
  'dailyTrends' : IDL.Vec(MarketSummary),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMarket' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addPriceRecord' : IDL.Func(
      [IDL.Nat, CropType, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'createAlert' : IDL.Func([IDL.Nat, CropType, IDL.Nat, IDL.Bool], [], []),
  'deleteAlert' : IDL.Func([IDL.Nat, CropType, IDL.Nat, IDL.Bool], [], []),
  'deleteMarket' : IDL.Func([IDL.Nat], [], []),
  'getActiveAlerts' : IDL.Func([], [IDL.Vec(AlertCondition)], ['query']),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getAllPrices' : IDL.Func([], [IDL.Vec(PriceRecord)], ['query']),
  'getAllUserAlerts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(AlertCondition)))],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInactiveAlerts' : IDL.Func([], [IDL.Vec(AlertCondition)], ['query']),
  'getMarketPrices' : IDL.Func(
      [IDL.Nat, CropType],
      [IDL.Vec(PriceRecord)],
      ['query'],
    ),
  'getMarkets' : IDL.Func([], [IDL.Vec(Market)], ['query']),
  'getTNPrices' : IDL.Func([CropType], [IDL.Vec(LivePriceRecord)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(TransactionRecord)], ['query']),
  'getTrendsData' : IDL.Func([], [TrendsData], ['query']),
  'getUserAlerts' : IDL.Func([], [IDL.Vec(AlertCondition)], ['query']),
  'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationDelivered' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTransaction' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
  'sendNotification' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'toggleAlert' : IDL.Func([IDL.Nat, CropType, IDL.Nat, IDL.Bool], [], []),
  'updateMarket' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTNPriceCache' : IDL.Func([CropType, IDL.Vec(LivePriceRecord)], [], []),
  'validatePriceRecord' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CropType = IDL.Variant({ 'onion' : IDL.Null, 'groundnut' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlertCondition = IDL.Record({
    'active' : IDL.Bool,
    'above' : IDL.Bool,
    'targetPrice' : IDL.Nat,
    'marketId' : IDL.Nat,
    'cropType' : CropType,
    'isPersistent' : IDL.Bool,
  });
  const Time = IDL.Int;
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notificationType' : IDL.Text,
    'userPrincipal' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
    'delivered' : IDL.Bool,
  });
  const PriceRecord = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'date' : Time,
    'validated' : IDL.Bool,
    'pricePerKg' : IDL.Nat,
    'marketId' : IDL.Nat,
    'cropType' : CropType,
  });
  const NotificationPreference = IDL.Record({
    'notificationTypes' : IDL.Vec(IDL.Text),
    'smsEnabled' : IDL.Bool,
    'notificationFrequency' : IDL.Nat,
    'pushEnabled' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'notificationPreferences' : NotificationPreference,
    'name' : IDL.Text,
  });
  const Market = IDL.Record({
    'id' : IDL.Nat,
    'region' : IDL.Text,
    'name' : IDL.Text,
    'location' : IDL.Text,
  });
  const LivePriceRecord = IDL.Record({
    'region' : IDL.Text,
    'pricePerKg' : IDL.Nat,
    'state' : IDL.Text,
    'timestamp' : Time,
    'cropType' : CropType,
    'market' : IDL.Text,
  });
  const TransactionRecord = IDL.Record({
    'pricePerKg' : IDL.Float64,
    'mobileNumber' : IDL.Text,
    'weightKg' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'timestamp' : IDL.Int,
    'laborName' : IDL.Text,
    'farmerName' : IDL.Text,
  });
  const MarketSummary = IDL.Record({
    'averagePrice' : IDL.Nat,
    'maxPrice' : IDL.Nat,
    'priceTrend' : IDL.Vec(IDL.Nat),
    'minPrice' : IDL.Nat,
    'totalRecords' : IDL.Nat,
  });
  const TrendsData = IDL.Record({
    'monthlyTrends' : IDL.Vec(MarketSummary),
    'weeklyTrends' : IDL.Vec(MarketSummary),
    'dailyTrends' : IDL.Vec(MarketSummary),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMarket' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addPriceRecord' : IDL.Func(
        [IDL.Nat, CropType, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'createAlert' : IDL.Func([IDL.Nat, CropType, IDL.Nat, IDL.Bool], [], []),
    'deleteAlert' : IDL.Func([IDL.Nat, CropType, IDL.Nat, IDL.Bool], [], []),
    'deleteMarket' : IDL.Func([IDL.Nat], [], []),
    'getActiveAlerts' : IDL.Func([], [IDL.Vec(AlertCondition)], ['query']),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getAllPrices' : IDL.Func([], [IDL.Vec(PriceRecord)], ['query']),
    'getAllUserAlerts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(AlertCondition)))],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInactiveAlerts' : IDL.Func([], [IDL.Vec(AlertCondition)], ['query']),
    'getMarketPrices' : IDL.Func(
        [IDL.Nat, CropType],
        [IDL.Vec(PriceRecord)],
        ['query'],
      ),
    'getMarkets' : IDL.Func([], [IDL.Vec(Market)], ['query']),
    'getTNPrices' : IDL.Func([CropType], [IDL.Vec(LivePriceRecord)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(TransactionRecord)], ['query']),
    'getTrendsData' : IDL.Func([], [TrendsData], ['query']),
    'getUserAlerts' : IDL.Func([], [IDL.Vec(AlertCondition)], ['query']),
    'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationDelivered' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTransaction' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
    'sendNotification' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
    'toggleAlert' : IDL.Func([IDL.Nat, CropType, IDL.Nat, IDL.Bool], [], []),
    'updateMarket' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTNPriceCache' : IDL.Func(
        [CropType, IDL.Vec(LivePriceRecord)],
        [],
        [],
      ),
    'validatePriceRecord' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };