/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlertCondition {
  'active' : boolean,
  'above' : boolean,
  'targetPrice' : bigint,
  'marketId' : bigint,
  'cropType' : CropType,
  'isPersistent' : boolean,
}
export type CropType = { 'onion' : null } |
  { 'groundnut' : null };
export interface LivePriceRecord {
  'region' : string,
  'pricePerKg' : bigint,
  'state' : string,
  'timestamp' : Time,
  'cropType' : CropType,
  'market' : string,
}
export interface Market {
  'id' : bigint,
  'region' : string,
  'name' : string,
  'location' : string,
}
export interface MarketSummary {
  'averagePrice' : bigint,
  'maxPrice' : bigint,
  'priceTrend' : Array<bigint>,
  'minPrice' : bigint,
  'totalRecords' : bigint,
}
export interface Notification {
  'id' : bigint,
  'notificationType' : string,
  'userPrincipal' : Principal,
  'message' : string,
  'timestamp' : Time,
  'delivered' : boolean,
}
export interface NotificationPreference {
  'notificationTypes' : Array<string>,
  'smsEnabled' : boolean,
  'notificationFrequency' : bigint,
  'pushEnabled' : boolean,
}
export interface PriceRecord {
  'id' : bigint,
  'source' : string,
  'date' : Time,
  'validated' : boolean,
  'pricePerKg' : bigint,
  'marketId' : bigint,
  'cropType' : CropType,
}
export type Time = bigint;
export interface TransactionRecord {
  'pricePerKg' : number,
  'mobileNumber' : string,
  'weightKg' : number,
  'totalAmount' : number,
  'timestamp' : bigint,
  'laborName' : string,
  'farmerName' : string,
}
export interface TrendsData {
  'monthlyTrends' : Array<MarketSummary>,
  'weeklyTrends' : Array<MarketSummary>,
  'dailyTrends' : Array<MarketSummary>,
}
export interface UserProfile {
  'notificationPreferences' : NotificationPreference,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMarket' : ActorMethod<[string, string, string], bigint>,
  'addPriceRecord' : ActorMethod<[bigint, CropType, bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAdmin' : ActorMethod<[], boolean>,
  'createAlert' : ActorMethod<[bigint, CropType, bigint, boolean], undefined>,
  'deleteAlert' : ActorMethod<[bigint, CropType, bigint, boolean], undefined>,
  'deleteMarket' : ActorMethod<[bigint], undefined>,
  'getActiveAlerts' : ActorMethod<[], Array<AlertCondition>>,
  'getAllNotifications' : ActorMethod<[], Array<Notification>>,
  'getAllPrices' : ActorMethod<[], Array<PriceRecord>>,
  'getAllUserAlerts' : ActorMethod<
    [],
    Array<[Principal, Array<AlertCondition>]>
  >,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInactiveAlerts' : ActorMethod<[], Array<AlertCondition>>,
  'getMarketPrices' : ActorMethod<[bigint, CropType], Array<PriceRecord>>,
  'getMarkets' : ActorMethod<[], Array<Market>>,
  'getTNPrices' : ActorMethod<[CropType], Array<LivePriceRecord>>,
  'getTransactions' : ActorMethod<[], Array<TransactionRecord>>,
  'getTrendsData' : ActorMethod<[], TrendsData>,
  'getUserAlerts' : ActorMethod<[], Array<AlertCondition>>,
  'getUserNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationDelivered' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveTransaction' : ActorMethod<
    [string, string, number, number, number, string, bigint],
    undefined
  >,
  'sendNotification' : ActorMethod<[Principal, string, string], undefined>,
  'toggleAlert' : ActorMethod<[bigint, CropType, bigint, boolean], undefined>,
  'updateMarket' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateTNPriceCache' : ActorMethod<
    [CropType, Array<LivePriceRecord>],
    undefined
  >,
  'validatePriceRecord' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];