/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PriceRecord {
    id: bigint;
    source: string;
    date: Time;
    validated: boolean;
    pricePerKg: bigint;
    marketId: bigint;
    cropType: CropType;
}
export interface NotificationPreference {
    notificationTypes: Array<string>;
    smsEnabled: boolean;
    notificationFrequency: bigint;
    pushEnabled: boolean;
}
export interface TrendsData {
    monthlyTrends: Array<MarketSummary>;
    weeklyTrends: Array<MarketSummary>;
    dailyTrends: Array<MarketSummary>;
}
export type Time = bigint;
export interface AlertCondition {
    active: boolean;
    above: boolean;
    targetPrice: bigint;
    marketId: bigint;
    cropType: CropType;
    isPersistent: boolean;
}
export interface Notification {
    id: bigint;
    notificationType: string;
    userPrincipal: Principal;
    message: string;
    timestamp: Time;
    delivered: boolean;
}
export interface MarketSummary {
    averagePrice: bigint;
    maxPrice: bigint;
    priceTrend: Array<bigint>;
    minPrice: bigint;
    totalRecords: bigint;
}
export interface LivePriceRecord {
    region: string;
    pricePerKg: bigint;
    state: string;
    timestamp: Time;
    cropType: CropType;
    market: string;
}
export interface Market {
    id: bigint;
    region: string;
    name: string;
    location: string;
}
export interface UserProfile {
    notificationPreferences: NotificationPreference;
    name: string;
}
export interface TransactionRecord {
    pricePerKg: number;
    mobileNumber: string;
    weightKg: number;
    totalAmount: number;
    timestamp: bigint;
    laborName: string;
    farmerName: string;
}
export enum CropType {
    onion = "onion",
    groundnut = "groundnut"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMarket(name: string, location: string, region: string): Promise<bigint>;
    addPriceRecord(marketId: bigint, cropType: CropType, pricePerKg: bigint, source: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkAdmin(): Promise<boolean>;
    createAlert(marketId: bigint, cropType: CropType, targetPrice: bigint, above: boolean): Promise<void>;
    deleteAlert(marketId: bigint, cropType: CropType, targetPrice: bigint, above: boolean): Promise<void>;
    deleteMarket(marketId: bigint): Promise<void>;
    getActiveAlerts(): Promise<Array<AlertCondition>>;
    getAllNotifications(): Promise<Array<Notification>>;
    getAllPrices(): Promise<Array<PriceRecord>>;
    getAllUserAlerts(): Promise<Array<[Principal, Array<AlertCondition>]>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInactiveAlerts(): Promise<Array<AlertCondition>>;
    getMarketPrices(marketId: bigint, cropType: CropType): Promise<Array<PriceRecord>>;
    getMarkets(): Promise<Array<Market>>;
    getTNPrices(cropType: CropType): Promise<Array<LivePriceRecord>>;
    getTransactions(): Promise<Array<TransactionRecord>>;
    getTrendsData(): Promise<TrendsData>;
    getUserAlerts(): Promise<Array<AlertCondition>>;
    getUserNotifications(): Promise<Array<Notification>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationDelivered(notificationId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveTransaction(farmerName: string, laborName: string, weightKg: number, pricePerKg: number, totalAmount: number, mobileNumber: string, timestamp: bigint): Promise<void>;
    sendNotification(userPrincipal: Principal, message: string, notificationType: string): Promise<void>;
    toggleAlert(marketId: bigint, cropType: CropType, targetPrice: bigint, above: boolean): Promise<void>;
    updateMarket(marketId: bigint, name: string, location: string, region: string): Promise<void>;
    updateTNPriceCache(cropType: CropType, prices: Array<LivePriceRecord>): Promise<void>;
    validatePriceRecord(recordId: bigint): Promise<void>;
}
import type { AlertCondition as _AlertCondition, CropType as _CropType, LivePriceRecord as _LivePriceRecord, PriceRecord as _PriceRecord, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMarket(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMarket(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMarket(arg0, arg1, arg2);
            return result;
        }
    }
    async addPriceRecord(arg0: bigint, arg1: CropType, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPriceRecord(arg0, to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPriceRecord(arg0, to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAdmin();
            return result;
        }
    }
    async createAlert(arg0: bigint, arg1: CropType, arg2: bigint, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(arg0, to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(arg0, to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async deleteAlert(arg0: bigint, arg1: CropType, arg2: bigint, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlert(arg0, to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlert(arg0, to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async deleteMarket(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMarket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMarket(arg0);
            return result;
        }
    }
    async getActiveAlerts(): Promise<Array<AlertCondition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAlerts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAlerts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotifications();
            return result;
        }
    }
    async getAllPrices(): Promise<Array<PriceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrices();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrices();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserAlerts(): Promise<Array<[Principal, Array<AlertCondition>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserAlerts();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserAlerts();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInactiveAlerts(): Promise<Array<AlertCondition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInactiveAlerts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInactiveAlerts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketPrices(arg0: bigint, arg1: CropType): Promise<Array<PriceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketPrices(arg0, to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketPrices(arg0, to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarkets(): Promise<Array<Market>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarkets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarkets();
            return result;
        }
    }
    async getTNPrices(arg0: CropType): Promise<Array<LivePriceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTNPrices(to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTNPrices(to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(): Promise<Array<TransactionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return result;
        }
    }
    async getTrendsData(): Promise<TrendsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendsData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendsData();
            return result;
        }
    }
    async getUserAlerts(): Promise<Array<AlertCondition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAlerts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAlerts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNotifications();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationDelivered(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationDelivered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationDelivered(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveTransaction(arg0: string, arg1: string, arg2: number, arg3: number, arg4: number, arg5: string, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTransaction(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTransaction(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async sendNotification(arg0: Principal, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendNotification(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendNotification(arg0, arg1, arg2);
            return result;
        }
    }
    async toggleAlert(arg0: bigint, arg1: CropType, arg2: bigint, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAlert(arg0, to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAlert(arg0, to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async updateMarket(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMarket(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMarket(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTNPriceCache(arg0: CropType, arg1: Array<LivePriceRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTNPriceCache(to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg0), to_candid_vec_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTNPriceCache(to_candid_CropType_n1(this._uploadFile, this._downloadFile, arg0), to_candid_vec_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async validatePriceRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validatePriceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validatePriceRecord(arg0);
            return result;
        }
    }
}
function from_candid_AlertCondition_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertCondition): AlertCondition {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_CropType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropType): CropType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_LivePriceRecord_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LivePriceRecord): LivePriceRecord {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PriceRecord_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceRecord): PriceRecord {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    source: string;
    date: _Time;
    validated: boolean;
    pricePerKg: bigint;
    marketId: bigint;
    cropType: _CropType;
}): {
    id: bigint;
    source: string;
    date: Time;
    validated: boolean;
    pricePerKg: bigint;
    marketId: bigint;
    cropType: CropType;
} {
    return {
        id: value.id,
        source: value.source,
        date: value.date,
        validated: value.validated,
        pricePerKg: value.pricePerKg,
        marketId: value.marketId,
        cropType: from_candid_CropType_n8(_uploadFile, _downloadFile, value.cropType)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: string;
    pricePerKg: bigint;
    state: string;
    timestamp: _Time;
    cropType: _CropType;
    market: string;
}): {
    region: string;
    pricePerKg: bigint;
    state: string;
    timestamp: Time;
    cropType: CropType;
    market: string;
} {
    return {
        region: value.region,
        pricePerKg: value.pricePerKg,
        state: value.state,
        timestamp: value.timestamp,
        cropType: from_candid_CropType_n8(_uploadFile, _downloadFile, value.cropType),
        market: value.market
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    above: boolean;
    targetPrice: bigint;
    marketId: bigint;
    cropType: _CropType;
    isPersistent: boolean;
}): {
    active: boolean;
    above: boolean;
    targetPrice: bigint;
    marketId: bigint;
    cropType: CropType;
    isPersistent: boolean;
} {
    return {
        active: value.active,
        above: value.above,
        targetPrice: value.targetPrice,
        marketId: value.marketId,
        cropType: from_candid_CropType_n8(_uploadFile, _downloadFile, value.cropType),
        isPersistent: value.isPersistent
    };
}
function from_candid_tuple_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_AlertCondition>]): [Principal, Array<AlertCondition>] {
    return [
        value[0],
        from_candid_vec_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onion: null;
} | {
    groundnut: null;
}): CropType {
    return "onion" in value ? CropType.onion : "groundnut" in value ? CropType.groundnut : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PriceRecord>): Array<PriceRecord> {
    return value.map((x)=>from_candid_PriceRecord_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_AlertCondition>]>): Array<[Principal, Array<AlertCondition>]> {
    return value.map((x)=>from_candid_tuple_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LivePriceRecord>): Array<LivePriceRecord> {
    return value.map((x)=>from_candid_LivePriceRecord_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AlertCondition>): Array<AlertCondition> {
    return value.map((x)=>from_candid_AlertCondition_n6(_uploadFile, _downloadFile, x));
}
function to_candid_CropType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CropType): _CropType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_LivePriceRecord_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LivePriceRecord): _LivePriceRecord {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: string;
    pricePerKg: bigint;
    state: string;
    timestamp: Time;
    cropType: CropType;
    market: string;
}): {
    region: string;
    pricePerKg: bigint;
    state: string;
    timestamp: _Time;
    cropType: _CropType;
    market: string;
} {
    return {
        region: value.region,
        pricePerKg: value.pricePerKg,
        state: value.state,
        timestamp: value.timestamp,
        cropType: to_candid_CropType_n1(_uploadFile, _downloadFile, value.cropType),
        market: value.market
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CropType): {
    onion: null;
} | {
    groundnut: null;
} {
    return value == CropType.onion ? {
        onion: null
    } : value == CropType.groundnut ? {
        groundnut: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LivePriceRecord>): Array<_LivePriceRecord> {
    return value.map((x)=>to_candid_LivePriceRecord_n22(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
